"""add_date_of_birth_and_expand_unique_id_in_participant

Revision ID: 395b5ab2af4d
Revises: 5ab458200f39
Create Date: 2026-08-24 10:56:32.091805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395b5ab2af4d'
down_revision: Union[str, Sequence[str], None] = '5ab458200f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('date_of_birth', sa.String(length=20), nullable=False))
    op.alter_column('participants', 'unique_id',
               existing_type=sa.String(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'unique_id',
               existing_type=sa.String(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('participants', 'date_of_birth')
    # ### end Alembic commands ###
