"""init

Revision ID: 4af9a612c385
Revises: 
Create Date: 2026-08-14 12:58:21.845164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af9a612c385'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticket_sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('unique_id', sa.String(length=50), nullable=False),
    sa.Column('coupon_code', sa.String(length=20), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('has_won', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_coupon_code'), 'participants', ['coupon_code'], unique=True)
    op.create_index(op.f('ix_participants_ticket_sequence'), 'participants', ['ticket_sequence'], unique=True)
    op.create_index(op.f('ix_participants_unique_id'), 'participants', ['unique_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participants_unique_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_ticket_sequence'), table_name='participants')
    op.drop_index(op.f('ix_participants_coupon_code'), table_name='participants')
    op.drop_table('participants')
    # ### end Alembic commands ###
