"""create_pekon_table

Revision ID: 5ab458200f39
Revises: 4af9a612c385
Create Date: 2026-08-24 09:24:09.389813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab458200f39'
down_revision: Union[str, Sequence[str], None] = '4af9a612c385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pekon',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kecamatan', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('has_won', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('coupon_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pekon_coupon_code'), 'pekon', ['coupon_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pekon_coupon_code'), table_name='pekon')
    op.drop_table('pekon')
    # ### end Alembic commands ###
